/* Generated by Together */

#ifndef EPROPERTYCOMBO_H
#define EPROPERTYCOMBO_H

#include "EIconTextButtonProperty.h"
#include <vector>

class EPropListCtrl;
class IPropertyHost;

class EPropertyCombo : public EIconTextButtonProperty
{

protected:

	CStringArray m_StringArray;
	std::vector<int> m_Values;
	std::vector<int> m_Separators;

public:

	EPropertyCombo( IPropertyHost* pHost , const CString& sName , int* pProperty );

	virtual bool OnCommand( EPropWnd* pParent , WPARAM wParam , LPARAM lParam );
	virtual bool HasButton();
	virtual CString GetTextValue();

	EPropertyCombo* AddString( const CString& s );
	EPropertyCombo* AddString( const CString& s , int nValue );

	EPropertyCombo* AddSeparator();

/*
 *  @brief   	GetCurrentSelected	 取得当前选择 
 *  @return 	int 当前选择索引
 */
	int GetCurrentSelected();

/*
 *  @brief   	IsCombo	 判断是否下拉框 
 *  @return 	virtual BOOL 是下拉框返回TRUE,不是下拉框返回FALSE
 */
	virtual BOOL IsCombo();

};
#endif //EPROPERTYCOMBO_H