//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by XJBrowser.rc
//
#define IDB_SELFAULT_QUERY              3
#define IDD_ABOUTBOX                    100
#define IDD_XJBROWSER_FORM              101
#define IDR_MAINFRAME                   128
#define IDR_XJBROWTYPE                  129
#define IDB_BUTTON_IMAGES               130
#define IDC_HSPLITBAR                   131
#define IDC_VSPLITBAR                   132
#define IDR_MENU_LOGVIEW                133
#define IDD_XJ_VIEW_BASE                134
#define IDD_XJ_VIEW_COMM                135
#define IDD_XJ_VIEW_ACTION              136
#define IDD_XJ_VIEW_ALARM               137
#define IDD_XJ_VIEW_FAULT               138
#define IDD_XJ_VIEW_OSC                 139
#define IDD_XJ_VIEW_DI                  140
#define IDD_XJ_VIEW_PTCOMM              141
#define IDD_XJ_VIEW_PTRUN               142
#define IDD_XJ_VIEW_SYSALARM            143
#define IDD_XJ_VIEW_ACTION_DETAIL       146
#define IDD_XJ_VIEW_ALARM_DETAIL        147
#define IDD_XJ_VIEW_FAULT_QUERY         148
#define IDD_XJ_VIEW_FAULT_DETAIL        149
#define IDI_ICON1                       151
#define IDI_KEY                         151
#define IDI_SEARCH                      152
#define IDD_PT_GENERAL                  153
#define IDD_PT_SETTING                  154
#define IDD_PT_DIGITAL                  155
#define IDD_PT_SOFTBOARD                156
#define IDD_PT_ANALOG                   157
#define IDD_PT_ACTION                   158
#define IDD_PT_ALARM                    159
#define IDD_PT_OSC                      160
#define IDD_WAVEREC_GENERAL             161
#define IDD_WAVEREC_SETTING             162
#define IDD_WAVEREC_OSC                 163
#define IDD_XJ_DEVICE_VIEW              164
#define IDD_VALIDATE_ID                 166
#define IDD_CHECK                       167
#define IDR_MENU_MAP_SVG                169
#define IDR_MENU_FIGURE_PROTECT         170
#define IDR_MENU_FIGURE_WAVEREC         171
#define IDD_EVENT_PROP                  172
#define IDR_MENU_EVENTVIEW              173
#define IDR_MENU_STATION                174
#define IDD_DLG_EVENT_SIGNAL            175
#define IDD_SIGNAL_LIST                 176
#define IDD_DLG_BATCH                   177
#define IDR_MENU_FAULTREPORT            178
#define IDD_BATCH_SELECT                179
#define IDD_BATCH_DETAIL                180
#define IDR_MENU_BATCH                  181
#define IDR_GIF_WAIT                    182
#define IDD_PT_OSCLIST                  184
#define IDB_BMP_WAIT                    185
#define IDD_XJ_VIEW_SYSALARM_DETAIL     186
#define IDD_DLG_FAULT                   187
#define IDD_DLG_FAULTEVENT              188
#define IDD_AUTOCALL_RESULT             189
#define IDD_DLG_OCSET                   190
#define IDR_MENU_TREE_STATION           191
#define IDD_DLG_SELECTSTATION_SVGPATH   192
#define IDR_XJBROWMAP                   193
#define IDB_TOOL1_NOR                   195
#define IDB_TOOL1_G                     196
#define IDB_BMP_START                   197
#define IDD_ABOUT                       199
#define IDB_BMP_SUNTECH                 200
#define IDD_PT_HISTORY                  201
#define IDD_PAGE_SYS_GENERAL            202
#define IDD_PAGE_SYS_INFOCASE           203
#define IDD_PAGE_SYS_STATUS             204
#define IDD_PAGE_SYS_PTPROP             205
#define IDR_MENU_SETTING_PRINT          206
#define IDR_MENU_ROUTINE_PRINT          207
#define IDD_DOWNLOAD_FILE               208
#define IDD_ACRESULTSEL                 209
#define IDR_MENU_RESULT                 210
#define IDR_MENU_PTCOMM                 211
#define IDR_MENU_PTRUN                  212
#define IDD_AUTOCALL_STOP               213
#define IDD_XJ_VIEW_CROSS               215
#define IDD_XJ_VIEW_CROSS_DETAIL        216
#define IDD_XJ_VIEW_SOE                 217
#define IDD_XJ_VIEW_SOE_DETAIL          218
#define IDB_BITMAP_TREE                 219
#define IDR_MENU_PROTECT                220
#define IDR_MENU_WAVEREC                221
#define IDD_PTSTATUS_HISTORY            222
#define IDR_MENU_GEO                    223
#define IDD_XJ_VIEW_STATIONINFO         224
#define IDR_MENU_STATIONINFO            225
#define IDR_MENU_AUTOCALL               226
#define IDD_DOWNLOAD_OSC                227
#define IDR_MENU_DOWNOSC                228
#define IDI_ACK                         230
#define IDI_EVENT                       231
#define IDI_WAVE                        232
#define IDI_PRINT                       233
#define IDI_SAVE                        234
#define IDI_VIEWFILE                    235
#define IDI_REFRESH                     236
#define IDI_HISTORY                     237
#define IDI_MODIFY                      238
#define IDI_CONTROL                     239
#define IDC_PAN                         241
#define IDD_DLG_ADDOSC                  242
#define IDD_DIALOG_DevRunStatusUpdate   243
#define IDD_DLG_DevRunStatusUpdate      243
#define IDD_BATCH_SETTING               245
#define IDD_BATCH_DETAIL_SETTING        247
#define IDR_MENU_BATCH_SETTING          248
#define IDD_DLG_DEVICE_LIST             249
#define IDD_DLG_DETAIL_STATUS           250
#define IDD_DIALOG1                     256
#define IDB_BMP_LOGO                    258
#define IDB_BMP_LOGIN                   259
#define IDB_BMP_ABOUT                   260
#define IDB_LIST_BK                     261
#define IDC_HAND_MOUSE                  262
#define IDD_DIALOG_LOGO                 265
#define IDB_BITMAP_TOOL                 266
#define IDB_BMP_LOGO2                   267
#define IDD_DIALOG_LOGO2                268
#define IDB_BITMAP_TOOL2                269
#define IDB_BITMAP_TREE1                270
#define IDD_DIALOG_LOGO3                271
#define IDB_BITMAP_TREE2                272
#define IDD_PAGE_SYS_CUSTOM             273
#define IDB_BMP_LOGIN2                  274
#define IDI_RED_LIGHT                   275
#define IDI_GREEN_LIGHT                 276
#define IDD_DLG_MANUAL_FAULTSHORTEN     277
#define IDR_MENU_MAP                    278
#define IDD_DLG_SETTING_DETAIL          279
#define IDI_KEY1                        281
#define IDI_TICK                        284
#define IDD_PAGE_SYS_BROWSER            285
#define IDD_DLG_APP                     287
#define IDD_DLG_WORK                    288
#define IDD_DLG_STATION                 289
#define IDD_XJ_VIEW_STAINFO             290
#define IDD_DLG_MARKED                  291
#define IDD_XJ_VIEW_DISTANCE            299
#define IDB_BMP_WNDBTN                  301
#define IDB_BMP_STATUSLIGHT             304
#define IDD_DLG_CHANNEL                 306
#define IDD_PT_DISTANCE                 320
#define IDR_MENU_DRAFT                  325
#define IDR_TOOLBAR_DRAFT               326
#define IDB_TOOLBAR_ZOOM_N              334
#define IDB_TOOLBAR_ZOOM_G              335
#define IDD_DLG_EXPORTPROCESS           336
#define IDD_DLG_DRAFT                   337
#define IDD_DLG_SELFAULT                340
#define IDC_BUTTON_DevRunStatus_OK      341
#define IDD_PT_NOTE                     342
#define IDD_DLG_PTNOTE                  343
#define IDD_CHECK_PRO                   344
#define IDC_BUTTON1                     1000
#define IDC_BTN_FAULT_QUERY             1000
#define IDC_BTN_PTOSC_RF                1000
#define IDC_BTN_PTACTION_ACK            1000
#define IDC_BTN_PTALARM_ACK             1000
#define IDC_BTN_PTANALOG_CALL           1000
#define IDC_BTN_PTDI_CALL               1000
#define IDC_BTN_PTSOFT_CALL             1000
#define IDC_BTN_PTSET_CALL              1000
#define IDC_BTN_PTGEN_CPU               1000
#define IDC_BTN_WROSC_OPEN              1000
#define IDC_BTN_WRSET_CALL              1000
#define IDC_BTN_WRGEN_MORE              1000
#define IDC_BTN_ACK                     1000
#define IDC_BTN_EVENTSIGN_PRINT         1000
#define IDC_BTN_BATCH_PT_ALL            1000
#define IDC_BTN_BATCH_CALL              1000
#define IDC_BTN_PTOSCLIST_CALL          1000
#define IDC_DLG_FAULT_ADD               1000
#define IDC_DLG_FAULTEVENT_QUERY        1000
#define IDC_BTN_STATIONSVG_ADD          1000
#define IDC_BTN_PTHISTORY_CALL          1000
#define IDC_BTN_VIEWI_COLOR             1000
#define IDC_BTN_COMM_OFF_COLOR          1000
#define IDC_BTN_DOWNLOAD_CALL           1000
#define IDC_BTN_RESULT_EXPORT           1000
#define IDC_BTN_AUTOCALL_STOP           1000
#define IDC_BTN_ADDOSC_SKIN             1000
#define IDC_LIST_BATCH_DETAIL_SETTING   1000
#define IDC_BUTTON_ADD_STYLE            1000
#define IDC_BTN_BROWSER_WORK            1000
#define IDC_BTN_MARK                    1000
#define IDC_BTN_PTDISTANCE_DETAIL       1000
#define IDC_BTN_DRAFT                   1000
#define IDC_BTN_COMMMAP_BK              1000
#define IDC_BTN_NOTE_ADD                1000
#define IDC_LIST_ACTION                 1001
#define IDC_BTN_PTACTION_PRINT          1001
#define IDC_BTN_PTALARM_PRINT           1001
#define IDC_BTN_PTANALOG_PRINT          1001
#define IDC_BTN_PTDI_PRINT              1001
#define IDC_BTN_PTSOFT_PRINT            1001
#define IDC_BTN_PTSET_CALLZONE          1001
#define IDC_BTN_PTGEN_ONE               1001
#define IDC_BTN_WROSC_RF                1001
#define IDC_BTN_WRSET_PRINT             1001
#define IDC_BTN_WRGEN_REL               1001
#define IDC_BTN_FAULT_CONTINUE          1001
#define IDC_BTN_BATCH_SEL_NULL          1001
#define IDC_BTN_VIEWII_COLOR            1001
#define IDC_BTN_COMM_ON_COLOR           1001
#define IDC_BTN_DOWNLOAD_DOWN           1001
#define IDC_BTN_PTHISTORY_SAVE          1001
#define IDC_DLG_FAULT_ADDOSC            1001
#define IDC_BTN_BATCH_SETTING_CALL      1001
#define IDC_BTN_TOOLBAR_BK              1001
#define IDC_BTN_PTDISTANCE_ACK          1001
#define IDC_BTN_COMMMAP_FONTCOLOR       1001
#define IDC_LIST_ALARM                  1002
#define IDC_BTN_PTACTION_ACKALL         1002
#define IDC_BTN_PTALARM_ACKALL          1002
#define IDC_BTN_PTANALOG_STYLE          1002
#define IDC_BTN_PTDI_STYLE              1002
#define IDC_BTN_PTSOFT_STYLE            1002
#define IDC_BTN_PTSET_PRINT             1002
#define IDC_BTN_PTGEN_MORE              1002
#define IDC_BTN_WRGEN_START             1002
#define IDC_BTN_BATCH_SEL_PT            1002
#define IDC_BTN_VIEWIII_COLOR           1002
#define IDC_BTN_RUN_ON_COLOR            1002
#define IDC_BTN_BATCH_SETTING_SEL_NULL  1002
#define IDC_BTN_FILE_CLOSE              1002
#define IDC_BTN_PTDISTANCE_ACKALL       1002
#define IDC_BTN_PTHISTORY_FAULT         1002
#define IDC_BTN_PTACTION_DETAIL         1003
#define IDC_BTN_PTALARM_SIGN            1003
#define IDC_BTN_PTSOFT_MODIFY           1003
#define IDC_BTN_PTSET_STYLE             1003
#define IDC_BTN_WRSET_STYLE             1003
#define IDC_BTN_WRGEN_TIME              1003
#define IDC_BTN_PTGEN_TIME              1003
#define IDC_BTN_BATCH_SEL_WR            1003
#define IDC_BTN_RUN_CHECK_COLOR         1003
#define IDC_BTN_BATCH_SETTING_SEL_PT    1003
#define IDC_BTN_DOWNLOAD_OPEN           1003
#define IDC_BTN_PTDISTANCE_PRINT        1003
#define IDC_BTN_PTANALOG_EXCEL          1003
#define IDC_BTN_PTDI_EXCEL              1003
#define IDC_BTN_PTACTION_SIGN           1004
#define IDC_BTN_PTALARM_DETAIL          1004
#define IDC_BTN_PTSET_ZONE_MODIFY       1004
#define IDC_BTN_PTGEN_SETTIME           1004
#define IDC_BTN_BATCH_SAVE_AS           1004
#define IDC_BTN_RUN_OFF_COLOR           1004
#define IDC_BTN_WRGEN_COMMHIS           1004
#define IDC_BTN_BATCH_SETTING_SEL_WR    1004
#define IDC_BTN_PTSOFT_EXCEL            1004
#define IDC_BTN_PTSET_MODIFY            1005
#define IDC_BTN_PTGEN_RESET             1005
#define IDC_BTN_BATCH_SAVE              1005
#define IDC_BTN_RUN_DEBUG_COLOR         1005
#define IDC_BTN_WRGEN_RUNHIS            1005
#define IDC_BTN_BATCH_SETTING_SAVE_AS   1005
#define IDC_BTN_AUTO_CALL_RESULT        1005
#define IDC_BTN_PTSOFT_VERIFY1          1005
#define IDC_BTN_PTACTION_EXCEL          1005
#define IDC_BTN_PTALARM_EXCEL           1005
#define IDC_EDIT_ALARM_1                1006
#define IDC_BTN_PTGEN_GEN               1006
#define IDC_BTN_BATCH_SET               1006
#define IDC_BTN_RUN_CODE_COLOR          1006
#define IDC_BTN_BATCH_SETTING_SAVE      1006
#define IDC_BTN_WRGEN_CALL              1006
#define IDC_BTN_PTSET_ZONE_RUN          1006
#define IDC_BTN_PTSOFT_VERIFY2          1006
#define IDC_EDIT_ALARM_2                1007
#define IDC_BTN_PTGEN_COMMHIS           1007
#define IDC_BTN_BATCH_SETTING_SET       1007
#define IDC_BTN_CLOSE                   1007
#define IDC_BTN_START_PIC               1007
#define IDC_BTN_PTSET_VERIFY1           1007
#define IDC_EDIT_ALARM_3                1008
#define IDC_BTN_PTGEN_RUNHIS            1008
#define IDC_BTN_BATCH_SETTING_RESET     1008
#define IDC_BTN_PTSET_VERIFY2           1008
#define IDC_STATIC_ALARM_1              1009
#define IDC_BTN_BATCH_SETTING_DEVICE_LIST 1009
#define IDC_BTN_PTGEN_CALL              1009
#define IDC_BTN_PTSET_EXCEL             1009
#define IDC_STATIC_ALARM_2              1010
#define IDC_BTN_CALL_STOP               1010
#define IDC_BTN_PTGEN_SUSPEND           1010
#define IDC_STATIC_ALARM_3              1011
#define IDC_BTN_AUTO_CLOSE              1011
#define IDC_STATIC_ACTION_1             1012
#define IDC_EDIT_ACTION_1               1013
#define IDC_STATIC_ACTION_2             1014
#define IDC_EDIT_ACTION_2               1015
#define IDC_STATIC_ACTION_3             1016
#define IDC_EDIT_ACTION_3               1017
#define IDC_LIST_OSC                    1018
#define IDC_LIST_DI                     1019
#define IDC_LIST_PTCOMM                 1020
#define IDC_LIST_PTRun                  1021
#define IDC_LIST_SYSALARM               1022
#define IDC_LIST_COMM                   1023
#define IDC_LIST_FAULT_NEW              1030
#define IDC_CMB_FAULT_STATION           1031
#define IDC_STATIC_FAULT_STATION        1032
#define IDC_STATIC_FAULT_ONE            1033
#define IDC_CMB_FAULT_ONE               1034
#define IDC_STATIC_FAULT_SEC            1035
#define IDC_CMB_FAULT_SAVE              1035
#define IDC_CMB_FAULT_SEC               1036
#define IDC_STATIC_FAULT_NET            1036
#define IDC_STATIC_FAULT_TIME1          1037
#define IDC_CMB_FAULT_TIME1             1038
#define IDC_CMB_FAULT_NET               1038
#define IDC_CMB_FAULT_TIME2             1039
#define IDC_STATIC_FAULT_VOLTAGE        1039
#define IDC_STATIC_FAULT_TYPE           1040
#define IDC_CMB_FAULT_TYPE              1041
#define IDC_LIST_FAULT_QUERY            1042
#define IDC_STATIC_FAULT_TIME2          1043
#define IDC_STATIC_PTOSC_DIR            1044
#define IDC_STATIC_FAULT_SAVE           1044
#define IDC_CHECK_PTOSC_SHOWALL         1045
#define IDC_CHECK_PTOSC_SHOW            1045
#define IDC_CMB_FAULT_VOLTAGE           1045
#define IDC_LIST_PTOSC                  1046
#define IDC_STATIC_FAULT_SECOND         1046
#define IDC_BTN_PTOSC_OPEN              1047
#define IDC_CMB_FAULT_SECOND            1047
#define IDC_CHECK_PTACTION_HIDE         1048
#define IDC_STATIC_FAULT_DEVICE_TYPE    1048
#define IDC_LIST_PTACTION               1049
#define IDC_CMB_FAULT_DEVICE_TYPE       1049
#define IDC_CHECK_PTALARM_HIDE          1050
#define IDC_STATIC_FAULT_TYPE2          1050
#define IDC_LIST_PTALARM                1051
#define IDC_CMB_FAULT_TYPE2             1051
#define IDC_LIST_PTANALOG               1052
#define IDC_STATIC_FAULT_OVERHAUL       1052
#define IDC_STATIC_PTANALOG             1053
#define IDC_CMB_FAULT_OVERHAUL          1053
#define IDC_CMB_PTANALOG_CPU            1054
#define IDC_CMB_PTDI_CPU                1055
#define IDC_STATIC_PTDI                 1056
#define IDC_LIST_PTDI                   1057
#define IDC_CMB_PTSOFT_CPU              1058
#define IDC_STATIC_PTSOFT               1059
#define IDC_LIST_PTSOFT                 1060
#define IDC_CMB_PTSET_CPU               1061
#define IDC_STATIC_PTSET_CPU            1062
#define IDC_STATIC_PTSET_SRC            1063
#define IDC_CMB_PTSET_SRC               1064
#define IDC_STATIC_PTSET_CURZONE        1065
#define IDC_EDIT_PTSET_CURZONE          1066
#define IDC_STATIC_PTSET_SELZONE        1067
#define IDC_STATIC_PTSET_EDITZONE       1068
#define IDC_CMB_PTSET_SELZONE           1069
#define IDC_TAB_PTSET                   1070
#define IDC_LIST_PTSET                  1071
#define IDC_STATIC_PTGEN_ONE            1072
#define IDC_EDIT_PTSET_EDITZONE         1072
#define IDC_EDIT_PTGEN_ONE              1073
#define IDC_LIST_PTZONE                 1073
#define IDC_STATIC_PTGEN_TYPE           1074
#define IDC_EDIT_PTGEN_TYPE             1075
#define IDC_STATIC_PTGEN_COMM           1076
#define IDC_EDIT_PTGEN_COMM             1077
#define IDC_STATIC_PTGEN_RUN            1078
#define IDC_EDIT_PTGEN_RUN              1079
#define IDC_PTGEN_SP                    1080
#define IDC_STATIC_PTGEN_VER            1081
#define IDC_EDIT_PTGEN_VER              1082
#define IDC_STATIC_WROSC_DIR            1082
#define IDC_STATIC_PTGEN_TIME           1083
#define IDC_LIST_WROSC                  1083
#define IDC_EDIT_PTGEN_TIME             1084
#define IDC_CHECK_WROSC_SHOW            1084
#define IDC_STATIC_PTGEN_ADDR           1085
#define IDC_STATIC_WRSET_SRC            1085
#define IDC_STATIC_PTGEN_COM            1086
#define IDC_CMB_WRSET_SRC               1086
#define IDC_STATIC_PTGEN_COMPARAM       1087
#define IDC_STATIC_WRSET_CPU            1087
#define IDC_EDIT_PTGEN_ADDR             1088
#define IDC_CMB_WRSET_CPU               1088
#define IDC_EDIT_PTGEN_COM              1089
#define IDC_TAB_WRSET                   1089
#define IDC_EDIT_PTGEN_COMPARAM         1090
#define IDC_LIST_WRSET                  1090
#define IDC_STATIC_PTGEN_103ADDR        1091
#define IDC_STATIC_WRGEN_TYPE           1091
#define IDC_EDIT_PTGEN_103ADDR          1092
#define IDC_EDIT_WRGEN_TYPE             1092
#define IDC_STATIC_PTGEN_COMPRO         1093
#define IDC_STATIC_WRGEN_COMM           1093
#define IDC_EDIT_PTGEN_COMPRO           1094
#define IDC_EDIT_WRGEN_COMM             1094
#define IDC_STATIC_PTGEN_COMCHECK       1095
#define IDC_STATIC_WRGEN_RUN            1095
#define IDC_EDIT_PTGEN_COMCHECK         1096
#define IDC_EDIT_WRGEN_RUN              1096
#define IDC_STATIC_WRGEN_VER            1097
#define IDC_PTGEN_SP2                   1097
#define IDC_EDIT_WRGEN_VER              1098
#define IDC_PTGEN_SP3                   1098
#define IDC_GROUP_WRGEN                 1099
#define IDC_STATIC_PTGEN_IPA            1099
#define IDC_CMB_WRGEN_CPU               1100
#define IDC_EDIT_PTGEN_IPA              1100
#define IDC_WRGEN_SP                    1101
#define IDC_STATIC_PTGEN_IPB            1101
#define IDC_TREE_DEVICE                 1102
#define IDC_WRGEN_SP2                   1102
#define IDC_EDIT_PTGEN_IPB              1102
#define IDC_LIST_DEVICE                 1103
#define IDC_STATIC_PTGEN_PORTA          1103
#define IDC_EDT_USERNAME                1104
#define IDC_EDIT_PTGEN_PORTA            1104
#define IDC_EDT_PASSWORD                1105
#define IDC_STATIC_PTGEN_PORTB          1105
#define IDC_EDIT_CHECK                  1106
#define IDC_EDIT_PTGEN_PORTB            1106
#define IDC_STATIC_PTGEN_SUSPEND        1107
#define IDC_EDIT_PTGEN_SUSPEND          1108
#define IDC_EDT_EVENTCLASS              1109
#define IDC_EDT_TIME                    1110
#define IDC_EDT_SOURCE                  1111
#define IDC_EDT_DESCRIBE                1112
#define IDC_TXT_RECORD                  1113
#define IDC_BTN_COPY                    1114
#define IDC_BTN_PREV                    1115
#define IDC_BTN_NEXT                    1116
#define IDC_GROUP_PTGEN                 1117
#define IDC_EDIT_PTGEN_INSIDETIME       1118
#define IDC_LIST_EVENTSIGN              1121
#define IDC_BTN_EVENTSIGN_COPY          1122
#define IDC_TAB_SIGNAL_LIST             1123
#define IDC_LIST_SIGNAL_LIST            1124
#define IDC_BATCH_TREE                  1125
#define IDC_CHECK_BATCH_SETTING         1127
#define IDC_CHECK_BATCH_DIGITAL         1128
#define IDC_CHECK_BATCH_ANALOG          1129
#define IDC_CHECK_BATCH_SOFTBOARD       1130
#define IDC_LIST_BATCH                  1131
#define IDC_BTN_BATCH_WR_ALL            1132
#define IDC_BTN_BATCH_NULL              1133
#define IDC_BTN_BATCH_LOAD              1134
#define IDC_DP_FAULT_TIME1              1137
#define IDC_DP_FAULT_TIME2              1138
#define IDC_STATIC_FAULT_RESULT         1139
#define IDC_STATIC_FAULT_RESULT2        1140
#define IDC_TREE_BATCH_SELECT           1140
#define IDC_LIST_BATCH_SELECT           1141
#define IDC_LIST_BATCH_DETAIL           1142
#define IDC_GIF_BATCH                   1143
#define IDC_GIF_PTANALOG                1144
#define IDC_GIF_PTDIGITAL               1145
#define IDC_GIF_PTGENERAL               1146
#define IDC_GIF_PTSET                   1147
#define IDC_GIF_PTSOFT                  1148
#define IDC_REMIND                      1148
#define IDC_GIF_WRSET                   1149
#define IDC_GIF_WRGEN                   1150
#define IDC_STATIC_PTOSCLIST_SRC        1151
#define IDC_CMB_PTOSCLIST_SRC           1152
#define IDC_STATIC_PTOSCLIST_START      1153
#define IDC_DP_PTOSCLIST_START          1154
#define IDC_DP_PTOSCLIST_END            1155
#define IDC_STATIC_PTOSCLIST_END        1156
#define IDC_LIST_PTOSCLIST              1157
#define IDC_BTN_PTOSCLIST_DOWN          1158
#define IDC_GIF_PTOSCLIST               1159
#define IDC_BTN_PTOSCLIST_OPEN          1160
#define IDC_STATIC_SYSALARM_1           1160
#define IDC_EDIT_SYSALARM_1             1161
#define IDC_BTN_PTOSCLIST_COPY          1161
#define IDC_STATIC_SYSALARM_2           1162
#define IDC_STATIC_SYSALARM_3           1163
#define IDC_EDIT_SYSALARM_3             1164
#define IDC_EDIT_SYSALARM_2             1165
#define IDC_DLG_FAULT_EDIT_NAME         1166
#define IDC_DLG_FAULT_TIME              1168
#define IDC_DLG_FAULT_CMB_DEVICE        1169
#define IDC_DLG_FAULT_EDIT_DIS          1170
#define IDC_DLG_FAULT_CMB_TYPE          1171
#define IDC_DLG_FAULT_CMB_STATION1      1172
#define IDC_DLG_FAULT_CMB_STATION2      1173
#define IDC_DLG_FAULT_TAB               1174
#define IDC_DLG_FAULT_REMOVE            1175
#define IDC_DLG_FAULT_LIST              1176
#define IDC_DLG_FAULT_CREATE_TIME       1177
#define IDC_DLG_FAULTEVENT_CMB_STATION  1178
#define IDC_DLG_FAULTEVENT_CMB_SEC      1179
#define IDC_DLG_FAULTEVENT_TIME1        1180
#define IDC_DLG_FAULTEVENT_TIME2        1181
#define IDC_DLG_FAULTEVENT_TAB          1182
#define IDC_DLG_FAULTITEM_LIST          1183
#define IDC_LIST_AUTOCALL_RESULT        1185
#define IDC_LIST_AUTOCALL_SUMMARY       1186
#define IDC_DLG_OCSET_TIME              1187
#define IDC_DLG_OCSET_CYC               1188
#define IDC_DLG_OCSET_SPIN              1189
#define IDC_DLG_OCSET_TYPE              1190
#define IDC_EDIT_STATION_SVGPATH        1191
#define IDC_BTN_STATIONSVG_DELETE       1192
#define IDC_EDIT_START_PIC              1192
#define IDC_STATIC_PTHISTORY_SRC        1193
#define IDC_CMB_PTHISTORY_SRC           1194
#define IDC_STATIC_PTHISTORY_START      1195
#define IDC_DP_PTHISTORY_START          1196
#define IDC_STATIC_PTHISTORY_END        1197
#define IDC_DP_PTHISTORY_END            1198
#define IDC_STATIC_PTHISTORY_TYPE       1199
#define IDC_CMB_PTHISTORY_TYPE          1200
#define IDC_GIF_PTHISTORY               1201
#define IDC_LIST_PTHISTORY              1202
#define IDC_CHECK_VIEWI                 1203
#define IDC_CHECK_VIEWI_POP             1204
#define IDC_CHECK_VIEWII                1205
#define IDC_CHECK_VIEWII_POP            1206
#define IDC_CHECK_VIEWIII               1207
#define IDC_CHECK_VIEWIII_POP           1208
#define IDC_CHECK_BLINKSEC              1209
#define IDC_EDIT_DevName                1209
#define IDC_CHECK_BLINKDEVICE           1210
#define IDC_CHECK_TOP_STATION           1211
#define IDC_CHECK_POP_WND               1212
#define IDC_CHECK_USE_SOUND             1213
#define IDC_EDIT_ALARMTIME              1214
#define IDC_CMB_SETTING_NUM             1215
#define IDC_EDIT_FLASHTIME              1215
#define IDC_CHECK_SETTING_GROUP         1216
#define IDC_CHECK_AUTOCHANGE            1216
#define IDC_CMB_SOFT_NUM                1217
#define IDC_CMB_DI_NUM                  1218
#define IDC_CMB_DI_VALUE                1220
#define IDC_CMB_SOFT_VALUE              1221
#define IDC_CHECK_PTAI                  1222
#define IDC_CHECK_DEVICETREE            1223
#define IDC_CHECK_OUTPUT                1224
#define IDC_CHECK_ACTIONDETAIL          1225
#define IDC_CHECK_SYSALARMDETAIL        1226
#define IDC_EDIT_PORT_AUTOCALL          1228
#define IDC_EDIT_AUTOCALLIP             1229
#define IDC_CMB_DOWN_STATION            1230
#define IDC_EDIT_STYLE_SETTING_NAME     1230
#define IDC_CMB_DOWN_CONDITION          1231
#define IDC_EDIT_DOWN_CONDITION         1232
#define IDC_DP_DOWN_TIME1               1233
#define IDC_DP_DOWN_TIME2               1234
#define IDC_LIST_DOWN                   1235
#define IDC_STATIC_DOWNLOAD_1           1236
#define IDC_STATIC_DOWNLOAD_2           1237
#define IDC_BUTTON_DevRunStatus_Exit    1237
#define IDC_STATIC_DOWNLOAD_3           1238
#define IDC_COMBO_DevRunUpdate_Status   1238
#define IDC_STATIC_DOWNLOAD_4           1239
#define IDC_EDIT_DevRunUpdate_Time      1239
#define IDC_STATIC_DOWNLOAD_5           1240
#define IDC_GIF_DOWNLOAD                1241
#define IDC_TREE_ACRESULTSEL            1242
#define IDC_TREE_AUTOCAL_STOP           1243
#define IDC_LIST_AUOTCALL_STOP          1244
#define IDC_STATIC_TIME_PTSETTING       1245
#define IDC_STATIC_TIME_PTDI            1246
#define IDC_STATIC_TIME_PTAI            1247
#define IDC_STATIC_TIME_PTGEN           1248
#define IDC_STATIC_TIME_PTSB            1249
#define IDC_STATIC_TIME_PTLIST          1250
#define IDC_STATIC_TIME_PTHIS           1251
#define IDC_STATIC_TIME_WRSETTING       1252
#define IDC_STATIC_TIME_WRGEN           1253
#define IDC_STATIC_TIME_DOWN            1254
#define IDC_LIST_CROSS                  1259
#define IDC_STATIC_NUM_PTLIST           1260
#define IDC_LIST_CROSSDETAIL            1261
#define IDC_LIST_SOE                    1262
#define IDC_STATIC_SOE_1                1263
#define IDC_EDIT_SOE_1                  1264
#define IDC_STATIC_SOE_2                1265
#define IDC_EDIT_SOE_2                  1266
#define IDC_STATIC_SOE_3                1267
#define IDC_EDIT_SOE_3                  1268
#define IDC_LIST_PTSTATUS_HIS           1269
#define IDC_BTN_PTHISTORY_SEL_NULL      1270
#define IDC_BTN_PTHISTORY_SEL_ALL       1271
#define IDC_LIST_STATIONINFO            1271
#define IDC_CHECK_PTACTION_DEBUG        1272
#define IDC_BTN_PTHISTORY_SEL_COPY      1272
#define IDC_CHECK_PTACTION_RETURN       1273
#define IDC_CHECK_PTALARM_DEBUG         1274
#define IDC_CHECK_PTALARM_RETURN        1275
#define IDC_LIST_DOWN_OSC               1276
#define IDC_STATIC_SETTING_P1           1277
#define IDC_STATIC_PTALARM_P1           1278
#define IDC_STATIC_SETTING_P2           1279
#define IDC_STATIC_PTALARM_P2           1279
#define IDC_STATIC_PTACTION_P1          1279
#define IDC_STATIC_PTALARM_P3           1280
#define IDC_STATIC_PTACTION_P2          1280
#define IDC_STATIC_PTDI_P1              1280
#define IDC_STATIC_PTACTION_P3          1281
#define IDC_STATIC_PTDI_P2              1281
#define IDC_STATIC_PTAI_P1              1281
#define IDC_STATIC_PTAI_P2              1282
#define IDC_STATIC_PTSB_P1              1282
#define IDC_STATIC_PTSB_P2              1283
#define IDC_STATIC_PTHIS_P1             1283
#define IDC_STATIC_PTSB_P3              1284
#define IDC_STATIC_PTHIS_P2             1284
#define IDC_BTN_PTOSC_COPY              1284
#define IDC_STATIC_PTOSC_P1             1285
#define IDC_STATIC_PTOSC_P2             1286
#define IDC_STATIC_PTOL_P1              1286
#define IDC_STATIC_PTOL_P2              1287
#define IDC_LIST_ACTIONDETAIL_SIGN      1287
#define IDC_LIST_ACTIONDETAIL_CHR       1288
#define IDC_STATIC_ACTIONDETAIL_P       1289
#define IDC_LIST_SOEDETAIL_SIGN         1290
#define IDC_LIST_SOEDETAIL_CHR          1291
#define IDC_STATIC_SOEDETAIL_P          1292
#define IDC_STATIC_WRSETTING_P1         1293
#define IDC_STATIC_WRSETTING_P2         1294
#define IDC_STATIC_PTGEN_DEVTIME        1294
#define IDC_STATIC_PTGEN_SP1            1295
#define IDC_STATIC_WRGEN_CPU            1296
#define IDC_STATIC_PTGEN_CPU_VER        1296
#define IDC_LIST_SYSALARM_DETAIL        1297
#define IDC_STATIC_PTGEN_CPU_DES        1297
#define IDC_CMB_ADDOSC_STATION          1299
#define IDC_CMB_ADDOSC_SEC              1300
#define IDC_EDIT_ADDOSC_PATH            1301
#define IDC_BTN_ADDOSC_ADD              1303
#define IDC_BTN_ADDOSC_REMOVE           1304
#define IDC_BTN_ADDOSC_MODIFY           1305
#define IDC_LIST_ADDOSC                 1306
#define IDC_DP_ADDOSC_TIME              1307
#define IDC_EDIT_ADDOSC_MS              1308
#define IDC_DLG_CMB_FAULT_SAVE          1309
#define IDC_EDIT_FAULT_REASON           1312
#define IDC_TREE                        1314
#define IDC_GIF_BATCH_SETTING           1315
#define IDC_LIST_DETAIL_STATUS          1318
#define IDC_STATION_STATIC              1319
#define IDC_IP_MODE_STATIC              1320
#define IDC_BTN_BATCH_START_ALL_CALL    1327
#define IDC_BTN_BATCH_PROCESS           1328
#define IDC_COMBO_STYLE                 1329
#define IDC_BUTTON_DELETE_STYLE         1330
#define IDC_BTN_LIST_SPACE_COLOR        1331
#define IDC_BTN_LIST_HEAD_COLOR         1332
#define IDC_BTN_TREE_BK_COLOR           1333
#define IDC_BTN_TREE_TEXT_COLOR         1334
#define IDC_BTN_TITLE_LIGHT_COLOR       1335
#define IDC_BTN_TITLE_DEEP_COLOR        1336
#define IDC_EDIT_TOOLBAR_BK             1337
#define IDC_COMBO_STYLE_CHOSE           1338
#define IDC_COMM_LIGHT                  1339
#define IDC_STAT_LIGHT                  1340
#define IDC_DEVICE_TREE                 1341
#define IDC_ACTION_LIST                 1343
#define IDC_COMBO_PTGEN_CPU_VER         1345
#define IDC_COMBO_PTGEN_CPU_DES         1346
#define IDC_EDIT_NAME                   1346
#define IDC_LIST_VALUE                  1348
#define IDC_BTN_BROWSER_APP             1349
#define IDC_RICHEDIT_WORK               1352
#define IDC_LIST1                       1353
#define IDC_COMBO_DEVICE                1354
#define IDC_EDIT_STAPROP_NAME           1355
#define IDC_EDIT_STAPROP_NET            1356
#define IDC_STATIC_CHOOSESTATION        1356
#define IDC_EDIT_STAPROP_IP             1357
#define IDC_COMBO_CHOOSESTATION         1357
#define IDC_EDIT_STAPROP_PORT           1358
#define IDC_EDIT_STAPROP_PROTOCOL       1359
#define IDC_EDIT_STAPROP_GETWAY         1360
#define IDC_CHECK_SHOWREADY             1361
#define IDC_CHECK_SHOWDEBUG             1362
#define IDC_EDIT_STAPROP_MANUFACTURER   1362
#define IDC_CHECK_SHOWRETURN            1363
#define IDC_COMBO_VACHSTATION           1364
#define IDC_STATIC_VACHSTATION          1366
#define IDC_COMBO_CHOOSESTATIOIN        1370
#define IDC_CHECK_SHOWPTCOMMON          1376
#define IDC_CHECK_SHOWPTRUNOFF          1376
#define IDC_CHECK_SHOWPTCOMMOFF         1377
#define IDC_CHECK_SHOWPTRUNON           1377
#define IDC_CHECK_SHOWPTRUNCHECK        1378
#define IDC_CHECK_SHOWPTRUNDEBUG        1379
#define IDC_CHECK_SHOWPTRUNCODE         1380
#define IDC_CHECK_FAULT                 1381
#define IDC_LIST_STAINFO                1383
#define IDC_LIST2                       1384
#define IDC_STATIC_FAULT_TYPE3          1384
#define IDC_STATIC_FAULTPART            1385
#define IDC_BTN_UNMARK                  1386
#define IDC_CMB_MARKREASON              1387
#define IDC_CMB_USERNAME                1388
#define IDC_DLG_FAULTEVENT_CMB_SECTYPE  1390
#define IDC_DLG_FAULTEVENT_CMB_DEVICE   1391
#define IDC_CMB_TYPICALCASE             1392
#define IDC_DLG_FAULTEVENT_CMB_EVENTTYPE 1392
#define IDC_STATIC_TYPICALCASE          1393
#define IDC_LIST_DISTANCE               1394
#define IDC_EDIT_CS_IP                  1395
#define IDC_EDIT_CS_STATUS              1396
#define IDC_EDIT_CS_TIME                1397
#define IDC_EDIT_CS_TIME2               1398
#define IDC_EDIT_CS_STATION             1399
#define IDC_EDIT_CS_CHANNEL             1400
#define IDC_LIST_CS                     1401
#define IDC_STATIC_PTACTION_LOADING     1402
#define IDC_STATIC_PTALARM_LOADING      1403
#define IDC_STATIC_PTANALOG_LOADING     1404
#define IDC_STATIC_PTDIGITAL_LOADING    1405
#define IDC_STATIC_PTOSC_LOADING        1406
#define IDC_STATIC_PTSETTING_LOADING    1407
#define IDC_STATIC_PTSOFT_LOADING       1408
#define IDC_STATIC_PTGENERAL_LOADING    1409
#define IDC_CHECK_PTDISTANCE_HIDE       1410
#define IDC_STATIC_PTDISTANCE_P1        1411
#define IDC_STATIC_PTDISTANCE_P2        1412
#define IDC_STATIC_PTDISTANCE_P3        1413
#define IDC_LIST_PTDISTANCE             1414
#define IDC_STATIC_PTDISTANCE_LOADING   1415
#define IDC_EXPORT_PROGRESS             1416
#define IDC_STATIC_EXPORTRESULT         1417
#define IDC_LIST_DRAFTFILES             1418
#define IDC_DDVUECTRL1                  1419
#define IDC_CMB_COMMMAP_FONT            1420
#define IDC_CMB_COMMMAP_FONTSIZE        1421
#define IDC_LIST_FAULT                  1422
#define IDC_LIST_NOTES                  1423
#define IDC_EDIT_CONTENT                1425
#define IDC_BTN_PTSET_MODIFY_VIEWPROG   1426
#define IDC_STATIC_DESC                 1428
#define IDC_BTN_RUN_HANGOUT_COLOR       1429
#define IDB_TREELIST_BITMAP             8000
#define IDC_CURSOR_SIZE                 8002
#define IDB_TREELIST_CHECK              8003
#define IDB_TREELIST_LOCK               8004
#define IDC_CURSOR_BUTTON               8005
#define IDC_CURSOR_CHECK                8006
#define IDC_CURSOR_LOCK                 8007
#define IDB_TREELIST_TREE               8008
#define IDB_TREELIST_SORT               8009
#define IDB_TREELIST_HEADER             8010
#define IDC_CURSOR_SPLIT                8011
#define IDB_TREELIST_DISABLE            8011
#define IDC_CURSOR_VERT                 8012
#define IDC_CURSOR_HORZ                 8013
#define IDC_CURSOR_CROSS                8014
#define IDC_CURSOR_DROP                 8015
#define IDC_CURSOR_STOP                 8016
#define ID_LOG_CLEARALL                 32771
#define ID_LOG_SELECTALL                32772
#define ID_MAP_REFRESH                  32773
#define ID_MAP_ZOOMIN                   32774
#define ID_MAP_ZOOMOUT                  32775
#define ID_MAP_ZOOMFULL                 32776
#define ID_MAP_STOPALART                32777
#define ID_PT_GENERAL                   32778
#define ID_PT_SETTING                   32779
#define ID_PT_DIGITAL                   32780
#define ID_PT_SOFTBOARD                 32781
#define ID_PT_CALLANALOG                32782
#define ID_PT_ACTION                    32783
#define ID_PT_ALARM                     32784
#define ID_PT_OSC                       32785
#define ID_PT_SIGNALLIST                32786
#define ID_PT_HEVENT                    32787
#define ID_QUERY_EVENT                  32788
#define ID_WR_GENERAL                   32790
#define ID_WR_SETTING                   32791
#define ID_WR_OSC                       32792
#define ID_MAP_ZOOM_OLD                 32793
#define IDC_EVENT_COPY                  32794
#define IDC_EVENT_ACK                   32795
#define IDC_EVENT_ALL                   32796
#define IDC_EVENT_HIDE                  32797
#define IDC_EVENT_DEVICE                32798
#define IDC_EVENT_SEC                   32799
#define IDC_EVENT_PROP                  32800
#define IDC_EVENT_SEC_PROP              32802
#define IDC_STATION_MAP                 32803
#define IDC_STATION_HISTORY             32804
#define IDC_STATION_TREE                32805
#define IDC_EVENT_SIGN                  32806
#define IDC_FAULT_EDIT                  32807
#define IDC_FAULT_PRINT                 32808
#define ID_TEST                         32809
#define ID_TOOL_BATCH                   32809
#define ID_BATCH_REMOVE                 32810
#define ID_BATCH_REMOVE_ALL             32811
#define ID_BATCH_SEC_PROP               32812
#define ID_BATCH_SEC_MAP                32813
#define ID_BATCH_SETTING                32814
#define ID_BATCH_DIGITAL                32815
#define ID_BATCH_SOFTBOARD              32816
#define ID_BATCH_ANALOG                 32817
#define ID_TOOL_AUTOCALL                32818
#define ID_TOOL_AUTOCALL_RESULT         32819
#define ID_VIEW_DEVICETREE              32820
#define ID_VIEW_OUTPUT                  32821
#define ID_STTP_CONNECT                 32822
#define ID_STTP_DISCONNECT              32823
#define ID_SYS_LOGOUT                   32824
#define ID_TREE_OPENMAP                 32825
#define ID_TREE_SETPATH                 32826
#define ID_HELP_CONTENT                 32828
#define ID_SYS_EXIT                     32829
#define ID_SYS_SETTING                  32830
#define ID_SETTINGPRINT_NEW1            32831
#define ID_SETTINGPRINT_NEW2            32832
#define ID_SETTINGPRINT_NEW3            32833
#define ID_SETTINGPRINT_ORDER_1         32834
#define ID_SETTINGPRINT_ORDER_2         32835
#define ID_SETTINGPRINT_ORDER3          32836
#define ID_ROUTINEPRINT_NEW1            32837
#define ID_ROUTINEPRINT_NEW2            32838
#define ID_ROUTINEPRINT_NEW3            32839
#define TOOL_DOWNLOAD_FILE              32840
#define ID_TOOL_DOWNLOAD_FILE           32841
#define IDC_RESULT_EXPORT               32842
#define IDC_RESULT_PRINT                32843
#define IDC_PTCOMM_ON                   32844
#define IDC_PTCOMM_OFF                  32845
#define IDC_PTCOMM_HISTORY              32846
#define IDC_COMM_ON                     32847
#define IDC_COMM_OFF                    32848
#define IDC_PTRUN_ON                    32849
#define IDC_PTRUN_OFF                   32850
#define IDC_PTRUN_CHECK                 32851
#define IDC_PTRUN_DEBUG                 32852
#define IDC_PTRUN_CODE                  32853
#define IDC_PTRUN_HISTORY               32854
#define IDC_PTCOMM_PRINT                32855
#define IDC_PTCOMM_EXPORT               32856
#define IDC_PTRUN_EXPORT                32857
#define IDC_PTRUN_PRINT                 32858
#define IDC_COMM_EXPORT                 32859
#define IDC_COMM_PRINT                  32860
#define IDC_RESULT_PREV                 32861
#define IDC_RESULT_NEXT                 32862
#define ID_TOOL_AUTOCALL_STOP           32863
#define IDC_FAULT_WEB                   32864
#define ID_TOOL_MAINSVG                 32865
#define ID_TOOL_STATIONCOMM             32866
#define ID_TOOL_PTCOMM                  32867
#define ID_TOOL_FAULTREPORT             32868
#define ID_WR_DIGITAL                   32869
#define ID_WR_ANALOG                    32870
#define ID_WR_OSC_LIST                  32871
#define ID_PT_OSC_LIST                  32872
#define IDC_EVENT_Refresh               32873
#define IDC_FAULT_REFRESH               32874
#define IDC_PTCOMM_REFRESH              32875
#define IDC_PTRUN_REFRESH               32876
#define IDC_RESULT_SHOWFAILD            32877
#define ID_PT_GENERAL_NEW               32878
#define ID_PT_SETTING_NEW               32879
#define ID_PT_DIGITAL_NEW               32880
#define ID_PT_SOFTBOARD_NEW             32881
#define ID_PT_ANALOG_NEW                32882
#define ID_PT_ACTION_NEW                32883
#define ID_PT_ALARM_NEW                 32884
#define ID_PT_HISTORY_NEW               32885
#define ID_PT_OSC_NEW                   32886
#define ID_PT_OSC_LIST_NEW              32887
#define ID_WR_GENERAL_NEW               32888
#define ID_WR_SETTING_NEW               32889
#define ID_WR_DIGITAL_NEW               32890
#define ID_WR_ANALOG_NEW                32891
#define ID_WR_OSC_NEW                   32892
#define ID_WR_OSC_LIST_NEW              32893
#define IDC_EVENT_QUERYEVENT            32894
#define ID_TOOL_QUERYEVENT              32895
#define IDC_EVENT_FILTER_DEBUG          32899
#define ID_GEO_EDIT                     32900
#define ID_GEO_SAVE                     32901
#define ID_GEO_DELETE                   32902
#define ID_GEO_OPEN                     32903
#define ID_GEO_ZOOMIN                   32904
#define ID_GEO_ZOOMOUT                  32905
#define ID_GEO_LOCALTREE                32906
#define IDC_STATIONINFO_SEC             32907
#define IDC_STATIONINFO_COMM_H          32908
#define IDC_STATIONINFO_RUN_H           32909
#define IDC_STATIONINFO_PRINT           32911
#define IDC_STATIONINFO_EXCLEL          32912
#define IDC_STATIONINFO_REFRESH         32913
#define IDC_EVENT_FILTER_RETURN         32914
#define IDC_FAULT_RETURN                32915
#define ID_AUTOCALL_ACTIVE              32916
#define ID_AUTOCALL_ALL                 32917
#define ID_TOOL_QUERYALARM              32918
#define IDC_EVENT_OPENOSC               32919
#define IDC_EVENT_DOWNOSC               32920
#define IDC_DOWNOSC_DOWN                32921
#define IDC_DOWNOSC_CANCEL              32922
#define IDC_DOWNOSC_OPEN                32923
#define ID_BATCH_ZONE                   32924
#define IDC_FAULT_CREATE                32925
#define ID_MENUITEM_DevTree_PTRunUpdate 32926
#define IDC_DEVICE_LIST                 32928
#define ID_TREE_STATION_CONFIG_CHANGE   32929
#define IDC_FAULT_DELETE                32930
#define IDC_FAULT_EXPORT                32932
#define ID_TEST1                        32934
#define fafa                            32935
#define fsdfsd                          32936
#define ID_GEO_ZOOM_RETURN              32938
#define ID_FILE_DOWNLOAD                32939
#define ID_APP_CALL                     32940
#define ID_CALL_ALL                     32941
#define IDC_WIN_CLOSE                   32942
#define IDC_EXPORT_EXCEL                32943
#define ID_BATCH_CLOSE                  32945
#define ID_TOOL_PTSTAT                  32948
#define ID_TOOL_DI                      32949
#define ID_TOOL_ACTION_EVENT            32950
#define ID_TOOL_ALARM_EVENT             32951
#define ID_TOOL_OSC                     32952
#define ID_MANUAL_FAULTSHORTENN         32953
#define ID_COM_MAP                      32954
#define ID_TOOL_SYSALARM                32955
#define ID_TOOL_GEO                     32956
#define ID_VIEW_BACK                    32957
#define ID_VIEW_PROP                    32958
#define ID_TREE_STATION_PROP            32959
#define ID_TREE_STATION_ADD             32960
#define ID_DevTree_PTCONFIGCHANGED      32961
#define ID_DevTree_PTADD                32962
#define IDC_EVENT_FILTER_FAULT          32963
#define ID_TOOL_STATIONINFO             32964
#define ID_MARK_DEVICE                  32965
#define ID_MARK_PTDEVICE                32966
#define ID_TOOL_DISTANCE                32967
#define IDC_FAULT_ONLYSHOWOVERHAUL      32968
#define IDC_FAULT_ONLYSHOWSAVED         32969
#define IDC_ONLYSHOWTYPICAL             32970
#define IDC_FAULT_ONLYSHOWTYPICAL       32971
#define ID_TREE_STATION_TEST            32972
#define ID_BATCH_EXPORT                 32973
#define IDC_FAULT_SHOWDI                32975
#define ID_DRAFT_ZOOMOUT                32976
#define ID_DRAFT_ZOOMIN                 32977
#define ID_DRAFT_REAL                   32978
#define ID_DRAFT_WINDOW                 32979
#define IDC_RESULT_STATIONEXPORT        32980
#define ID_COM_REFRESH                  32981
#define ID_INDICATOR_STTPSTATE          61446
#define ID_INDICATOR_LOGINTIP           61447
#define IDS_VALIDATE_INPUT_USER         61448
#define IDS_VALIDATE_INPUT_PWD          61449
#define IDS_COMMON_EXPORT               61450
#define IDS_MODEL_AREA                  61451
#define IDS_MODEL_SUBSTATION            61452
#define IDS_COMMON_PRINT                61453
#define IDS_MODEL_PRIMARY               61454
#define IDS_MODEL_SECONDARY             61455
#define IDS_AUTOCALLRESULT_EXPORT_FAIL  61456
#define IDS_AUTOCALLRESULT_NUMBER       61457
#define IDS_MODEL_CPU                   61458
#define IDS_AUTOCALLRESULT_ZONE         61459
#define IDS_AUTOCALLRESULT_ZONE_NOTE    61460
#define IDS_AUTOCALLRESULT_SETTING      61461
#define IDS_AUTOCALLRESULT_SETTING_NOTE 61462
#define IDS_AUTOCALLRESULT_DIGITAL      61463
#define IDS_AUTOCALLRESULT_SOFT         61464
#define IDS_AUTOCALLRESULT_SOFT_NOTE    61465
#define IDS_AUTOCALLRESULT_ANALOG       61466
#define IDS_AUTOCALLRESULT_ANALOG_NOTE  61467
#define IDS_AUTOCALLRESULT_OSC          61468
#define IDS_AUTOCALLRESULT_OSC_NOTE     61469
#define IDS_AUTOCALLRESULT_HISEVENT     61470
#define IDS_AUTOCALLRESULT_HISEVENT_NOTE 61471
#define IDS_COMMON_FINISHTIME           61472
#define IDS_AUTOCALLRESULT_OVERVIEW     61473
#define IDS_AUTOCALLRESULT_RESOLUTION   61474
#define IDS_MODEL_MANUFACTURER          61475
#define IDS_MODEL_MANAGEMENT            61476
#define IDS_MODEL_MAINTENANCE           61477
#define IDS_AUTOCALLRESULT_DIGITAL_NOTE 61478
#define IDS_SECPROP_ZONE                61479
#define IDS_SECPROP_SETTING             61480
#define IDS_SECPROP_DIGITAL             61481
#define IDS_SECPROP_SOFT                61482
#define IDS_SECPROP_ANALOG              61483
#define IDS_SECPROP_OSC                 61484
#define IDS_SECPROP_HISTORYEVENT        61485
#define IDS_AUTOCALLRESULT_SUMMARY      61486
#define IDS_SECPROP_LOCALFILE           61487
#define IDS_SECPROP_REMOTEFILE          61488
#define IDS_COMMON_ITEM                 61489
#define IDS_CALLRESULT_NOTCALL          61490
#define IDS_CALLRESULT_SUCCESS          61491
#define IDS_COMMON_SUCCESS              61491
#define IDS_CALLRESULT_FAILED           61492
#define IDS_COMMON_FAILED               61492
#define IDS_CALLRESULT_NOSUPPORT        61493
#define IDS_CALLRESULT_NODATA           61494
#define IDS_AUTOCALLRESULT_TOTAL        61495
#define IDS_AUTOCALLRESULT_SUCCESS_NUM  61496
#define IDS_AUTOCALL_STARTTIME          61497
#define IDS_AUTOCALL_ENDTIME            61498
#define IDS_AUTOCALL_NOTSTART           61499
#define IDS_AUTOCALLRESULT_FAILED_NUM   61500
#define IDS_COMMON_DAY                  61501
#define IDS_COMMON_HOUR                 61502
#define IDS_COMMON_MINUTE               61503
#define IDS_AUTOCALLRESULT_TOTALTIME    61504
#define IDS_FUNC_AUTOCALL               61505
#define IDS_COMMON_EXPORT_SUCCESS       61506
#define IDS_COMMON_EXPORT_FAIL          61507
#define IDS_FUNC_AUTOCALLRESULT         61508
#define IDS_MODEL_RELAY                 61509
#define IDS_MODEL_RECORDER              61510
#define IDS_COMMON_DEVICETYPE           61511
#define IDS_CALLOPER_CALL               61512
#define IDS_CALLOPER_NOTCALL            61513
#define IDS_CALLOPER_NOTSUPPORT         61514
#define IDS_BTN_SELECTALL_RECORDER      61515
#define IDS_BTN_SELECTALL_RELAY         61516
#define IDS_BTN_UNSELECTALL_RECORDER    61517
#define IDS_BTN_UNSELECTALL_RELAY       61518
#define IDS_SAVECONFIG_SUCCESS          61519
#define IDS_SAVECONFIG_FAILED           61520
#define IDS_AUTOCALL_NOSELECTION        61521
#define IDS_AUTOCALL_NOTIFY_FAILED      61522
#define IDS_MODEL_BUS                   61533
#define IDS_MODEL_LINE                  61534
#define IDS_MODEL_BREAKER               61535
#define IDS_MODEL_GEN                   61536
#define IDS_MODEL_REACTOR               61537
#define IDS_MODEL_TRANS                 61538
#define IDS_MODEL_SWITCH                61539
#define IDS_MODEL_CAP                   61540
#define IDS_MODEL_PMS                   61541
#define IDS_MODEL_BAY                   61542
#define IDS_CALLOPER_SUSPEND            61543
#define IDS_BTN_CALL                    61544
#define IDS_BTN_CANCEL_CALL             61545
#define IDS_BTN_START_CALL              61546
#define IDS_COMMON_UPDATEDB_FAILED      61547
#define IDS_AUTOCALL_DISCONNECT         61548
#define IDS_FUNC_AUTOCALL_CONFIG        61549
#define IDS_DOWNLOAD_NOTSTART           61550
#define IDS_DOWNLOAD_COMPLETE           61551
#define IDS_DOWNLOAD_PARTIAL            61552
#define IDS_FUNC_COMMONFILE             61553
#define IDS_DEFAULT_FONT                61554
#define IDS_FUNC_COMMUSTATUS            61555
#define IDS_FUNC_RUNSTATUS              61556
#define IDS_COMMU_STATUS                61557
#define IDS_COMMU_MAIN_MACHINE          61558
#define IDS_COMMU_STANDBY_MACHINE       61559
#define IDS_COMMU_MAIN_CHANNEL          61560
#define IDS_COMMU_STANDBY_CHANNEL       61561
#define IDS_COMMU_ALONE                 61562
#define IDS_CROSSSTATUS_NORMAL          61563
#define IDS_CROSSSTATUS_ALERT           61564
#define IDS_COMMON_UNKNOWN              61565
#define IDS_CROSSSTATUS_RETURN          61566
#define IDS_STYLE_TOOLBAR_BKIMAGE       61567
#define IDS_STYLE_START_IMAGE           61568
#define IDS_MODEL_VIRTUALSTATION        61569
#define IDS_LOADING_STATIONREASON       61570
#define IDS_LOADING_AREA                61571
#define IDS_LOADING_STATION             61572
#define IDS_LOADING_SEPSTATION          61573
#define IDS_LOADING_BAY                 61574
#define IDS_LOADING_MANAGER             61575
#define IDS_LOADING_MAINTENANCE         61576
#define IDS_LOADING_SUSPENDREASON       61577
#define IDS_LOADING_BREAKER             61578
#define IDS_LOADING_BUS                 61579
#define IDS_LOADING_CAP                 61580
#define IDS_LOADING_GEN                 61581
#define IDS_LOADING_LINE                61582
#define IDS_LOADING_REACTOR             61583
#define IDS_LOADING_SWITCH              61584
#define IDS_LOADING_TRANS               61585
#define IDS_LOADING_PMS                 61586
#define IDS_LOADING_SEC                 61587
#define IDS_LOADING_CPU                 61588
#define IDS_LOADING_ZONE                61589
#define IDS_LOADING_UNICHR              61590
#define IDS_DISCONNECT_REASON_NORMAL    61592
#define IDS_DISCONNECT_REASON_STANDBY   61593
#define IDS_DISCONNECT_REASON_MACHINE   61594
#define IDS_DISCONNECT_REASON_GATEWAY   61595
#define IDS_DISCONNECT_REASON_NETWORK   61596
#define IDS_DISCONNECT_REASON_LINK      61597
#define IDS_DISCONNECT_REASON_UNKNOWN   61598
#define IDS_COMMON_EDIT                 61599
#define IDS_COMMUSTATUS_ON              61600
#define IDS_COMMUSTATUS_OFF             61601
#define IDS_RUNSTATUS_SERVICE           61602
#define IDS_RUNSTATUS_OVERHAULS         61603
#define IDS_RUNSTATUS_OUTAGE            61604
#define IDS_RUNSTATUS_TESTING           61605
#define IDS_RUNSTATUS_NOACCESS          61606
#define IDS_COMMON_UNUSED               61607
#define IDS_COMMON_PROPERTY             61608
#define IDS_COMMON_VALUE                61609
#define IDS_STAT_OFFDEVICE              61610
#define IDS_STAT_RUNABNORMAL            61611
#define IDS_COMMON_IP                   61612
#define IDS_COMMON_PROTOCOL             61613
#define IDS_STAT_OFFSTATION             61614
#define IDS_COMMON_DEVICENAME           61615
#define IDS_MODEL_GPS                   61616
#define IDS_MODEL_DISTANCE              61617
#define IDS_PERMISSION_SYSCONF          61618
#define IDS_PERMISSION_BROWSER          61619
#define IDS_PERMISSION_OPER             61620
#define IDS_PERMISSION_CONTROL          61621
#define IDS_PERMISSION_GUARD            61622
#define IDS_PERMISSION_CONFIG           61623
#define IDS_STATIONCHANGE_NOTIFY_SUCCESS 61624
#define IDS_STATIONCHANGE_NOTIFY_FAIL   61625
#define IDS_STATIONCHANGE_BUILD_FAIL    61626
#define IDS_NEWSTATION_NOTIFY_SUCCESS   61627
#define IDS_NEWSTATION_NOTIFY_FAIL      61628
#define IDS_NEWDEV_NOTIFY_SUCCESS       61629
#define IDS_NEWDEV_NOTIFY_FAIL          61630
#define IDS_STTP_DISCONNECT             61631
#define IDS_TESTSTATION_BUSY            61632
#define IDS_CALL_SENDMSG_SUCCESS        61633
#define IDS_CALL_SENDMSG_FAIL           61634
#define IDS_COMMU_CHANNEL               61635
#define IDS_CALLFAIL_SEND               61636
#define IDS_CALLFAIL_RESPONSE           61637
#define IDS_CALLFAIL_TIMEOUT            61638
#define IDS_SECPROP_GENERAL             61639
#define IDS_SECPROP_ACTION              61640
#define IDS_SECPROP_ALARM               61641
#define IDS_SECPROP_DISTANCE            61642
#define IDS_RUNSTATUSCHANGE_NOTIFY_SUCCESS 61643
#define IDS_RUNSTATUSCHANGE_NOTIFY_FAIL 61644
#define IDS_QUERY_RUNSTATUS_FAIL        61645
#define IDS_COMMON_NEEDSTATION          61646
#define IDS_COMMON_FAULTTIME            61647
#define IDS_COMMON_FILENAME             61648
#define IDS_ADDOSC_SELECTFILE           61649
#define IDS_ADDOSC_PATHERROR            61650
#define IDS_COMMON_NO                   61651
#define IDS_COMMON_VERSION              61652
#define IDS_COMMON_CHECKCODE            61653
#define IDS_APPMAINTAIN_PERSON          61654
#define IDS_APPMAINTAIN_TEL             61655
#define IDS_APPMAINTAIN_DATE            61656
#define IDS_APPMAINTAIN_CONTENT         61657
#define IDS_COMMON_NOTE                 61658
#define IDS_COMMON_BUILDMSG_FAIL        61659
#define IDS_STOPAUTOCALL_SELECTSTATION  61660
#define IDS_STOPAUTOCALL_SENDFAIL       61661
#define IDS_STOPAUTOCALL_SENDSUCCESS    61662
#define IDS_COMMON_TIME                 61663
#define IDS_DISCONNECT_REASON           61664
#define IDS_CHECK_GUARDIAN              61665
#define IDS_CHECK_OPERATOR              61666
#define IDS_CHECK_DEFAULT               61667
#define IDS_DISCONNECT_REASON_TIME      61668
#define IDS_STANDBYCHL_COMMU_STATUS     61669
#define IDS_STANDBYCHL_DISCONNECT_REASON 61670
#define IDS_STANDBYCHL_DISCONNECT_REASON_TIME 61671
#define IDS_COMMUMODE_ALONE             61672
#define IDS_COMMUMODE_DOUBLE_MACHINES   61673
#define IDS_COMMUMODE_DOUBLE_CHANNELS   61674
#define IDS_EVENT_PROPERTY              61675
#define IDS_EVENT_ACK_SUCCESS           61676
#define IDS_EVENT_ACK_FAIL              61677
#define IDS_EVENT_CIRCLE_END            61678
#define IDS_EVENT_CIRCLE_FRONT          61679
#define IDS_EVENTCOUNT_CURRENT          61680
#define IDS_EVENTCOUNT_TOTAL            61681
#define IDS_EVENT_PROP_NOTACK           61682
#define IDS_EVENTTYPE_ACTION            61683
#define IDS_EVENTTYPE_ALARM             61684
#define IDS_EVENTTYPE_SYSALARM          61685
#define IDS_EVENTTYPE_DI                61686
#define IDS_EVENTTYPE_OSC               61687
#define IDS_EVENTTYPE_FAULT             61688
#define IDS_EVENTTYPE_PTCOMM            61689
#define IDS_EVENTTYPE_PTRUN             61690
#define IDS_EVENTTYPE_DISTANCE          61691
#define IDS_COMMON_TYPE                 61692
#define IDS_FUN_ACTION                  61693
#define IDS_ACTION_CASE                 61694
#define IDS_CASE_ACTION                 61695
#define IDS_CASE_RETURN                 61696
#define IDS_TIP_SELECTITEM              61697
#define IDS_HEAD_FONT                   61698
#define IDS_EXPORT_FINISHED             61700
#define IDS_COMMON_ALL                  61701
#define IDS_FAULTEVENT_TYPE_CHAR        61702
#define IDS_FAULTEVENT_TYPE_ACTIONSIGNAL 61703
#define IDS_FAULTEVENT_TYPE_ALARMSIGNAL 61704
#define IDS_FAULTEVENT_TYPE_OSC         61705
#define IDS_FAULTEVENT_TYPE_DICHANGE    61706
#define IDS_EVENT_STARTTIME             61707
#define IDS_EVENT_RECIVETIME            61708
#define IDS_EVENT_DESC                  61709
#define IDS_EVENT_VALUE                 61710
#define IDS_EVENT_SIGNALTIME            61711
#define IDS_FAULT_REASON                61712
#define IDS_FAULTTYPE_UNKNOWN           61713
#define IDS_FAULTTYPE_A                 61714
#define IDS_FAULTTYPE_B                 61715
#define IDS_FAULTTYPE_C                 61716
#define IDS_FAULTTYPE_AB                61717
#define IDS_FAULTTYPE_BC                61718
#define IDS_FAULTTYPE_CA                61719
#define IDS_FAULTTYPE_ABN               61720
#define IDS_FAULTTYPE_BCN               61721
#define IDS_FAULTTYPE_CAN               61722
#define IDS_FAULTTYPE_ABC               61723
#define IDS_FAULTTYPE_ABCN              61724
#define IDS_FAULT_TYPE                  61725
#define IDS_COMMON_UNSPECIFIED          61726
#define IDS_COMMON_YES                  61727
#define IDS_COMMON_NOT                  61728
#define IDS_FAULTREASON_TOOLONG         61729
#define IDS_FAULTREPORT_UPDATE_FAIL     61730
#define IDS_FAULTEVENT_DELETE_FAIL      61731
#define IDS_FAULTEVENT_UPDATE_FAIL      61732
#define IDS_FAULTREPORT_SYNC_SUCCESS    61733
#define IDS_FAULTREPORT_SYNC_FAIL       61734
#define IDS_HANGOUT_SUCCESS             61735
#define IDS_UNHANGOUT_SUCCESS           61736
#define IDS_CYCLE_HOUR                  61737
#define IDS_CYCLE_DAY                   61738
#define IDS_CYCLE_MONTH                 61739
#define IDS_CYCLE_YEAR                  61740
#define IDS_SETTIME_FUTURE              61741
#define IDS_SETCYCLE_RANGE              61742
#define IDS_FAULTREPORT_NAME            61743
#define IDS_COMMON_CREATETIME           61744
#define IDS_FAULT_TIME                  61745
#define IDS_FAULT_DEVICE                61746
#define IDS_FAULT_STATION1              61747
#define IDS_FAULT_STATION2              61748
#define IDS_TIP_SELECT_ONEITEM          61749
#define IDS_SETTING_DESC                61750
#define IDS_SIGNAL_ACTION               61751
#define IDS_SIGNAL_ALARM                61752
#define IDS_SIGNAL_LIST                 61753
#define IDS_SIGNAL_NAME                 61754
#define IDS_SIGNAL_CODE                 61755
#define IDS_SIGNAL_TYPE                 61756
#define IDS_STATION_SELECT_SVG          61757
#define IDS_COMMUSTATUS_HISTORY         61758
#define IDS_RUNSTATUS_HISTORY           61759
#define IDS_STATUS_CHANGE_TIME          61760
#define IDS_STATUS_AFTER_CHANGE         61761
#define IDS_VALIDATE_GUARDIAN           61762
#define IDS_VALIDATE_OPERATOR           61763
#define IDS_VALIDATE_LOCKED             61764
#define IDS_VALIDATE_USERPWD_ERROR      61765
#define IDS_VALIDATE_MULTI_IDENTITY     61766
#define IDS_VALIDATE_AUTHORITY          61767
#define IDS_COMMONFILE_CONDITION_FILENAME 61768
#define IDS_COMMONFILE_CONDITION_TIME   61769
#define IDS_COMMON_FILESIZE             61770
#define IDS_COMMON_FILETIME             61771
#define IDS_DOWNLOAD_FINISHED           61772
#define IDS_FUNC_CALL_LIST              61773
#define IDS_FUNC_CALL_FILE              61774
#define IDS_COMMON_SPEND                61775
#define IDS_COMMON_SECOND               61776
#define IDS_COMMONFILE_LIST_CALL_FAIL   61777
#define IDS_COMMONFILE_LIST_CALL_TIMEOUT 61778
#define IDS_FUNC_CALL                   61779
#define IDS_DOWNLOAD_AGAIN              61780
#define IDS_DOWNLOAD_RESUME             61781
#define IDS_COMMONFILE_LIST_NOTSUPPORT  61782
#define IDS_COMMON_SELECTFORWATCH       61783
#define IDS_COMMON_FILE_NOTDOWNLOADED   61784
#define IDS_COMMON_NEED_DOWNLOAD        61785
#define IDS_FUNC_OSC_DOWNLOAD           61786
#define IDS_DRAFT_SUBSTATION            61787
#define IDS_DRAFT_OPEN_FAIL             61788
#define IDS_PHASE_NUM_ONE               61789
#define IDS_PHASE_NUM_TWO               61790
#define IDS_PHASE_NUM_THREE             61791
#define IDS_COMMON_PTTYPE               61792
#define IDS_ACK_ISACKED                 61793
#define IDS_ACK_YES                     61794
#define IDS_ACK_NO                      61795
#define IDS_COMMON_OCCUR_TIME           61796
#define IDS_FOLLOW_ALARM                61797
#define IDS_COMMON_MILLISECOND          61798
#define IDS_FOLLOW_SIGNAL               61799
#define IDS_FOLLOW_SAMPLE               61800
#define IDS_TRIP_PHASE                  61801
#define IDS_FAULT_LOCATION              61802
#define IDS_DOWNLOAD_FAIL               61803
#define IDS_DOWNLOAD_CANCEL             61804
#define IDS_FOLLOW_SUBSTATION_CHANGED   61805
#define IDS_STATIONCHANGED_ALL          61806
#define IDS_FOLLOW_SETTING              61807
#define IDS_FOLLOW_SOFTBOARD            61808
#define IDS_FOLLOW_ZONE                 61809
#define IDS_FOLLOW_ORDER                61810
#define IDS_SYSALARM_ZONE               61811
#define IDS_SYSALARM_SOFTBOARD          61812
#define IDS_SYSALARM_SETTING            61813
#define IDS_SYSALARM_ORDERSETTING       61814
#define IDS_SYSALARM_SUBSTATION         61815
#define IDS_SYSALARM_DISCONNECT         61816
#define IDS_SUBSTATION_CHANGE_LINE      61817
#define IDS_SUBSTATION_CHANGE_SECONDARY 61818
#define IDS_SUBSTATION_CHANGE_GROUPTITLE 61819
#define IDS_SUBSTATION_CHANGE_BREAKER   61820
#define IDS_SUBSTATION_CHANGE_BUS       61821
#define IDS_SUBSTATION_CHANGE_TRANS     61822
#define IDS_SUBSTATION_CHANGE_GEN       61823
#define IDS_SUBSTATION_CHANGE_REACTOR   61824
#define IDS_SUBSTATION_CHANGE_SWITCH    61825
#define IDS_SUBSTATION_CHANGE_NEW       61826
#define IDS_SUBSTATION_CHANGE_NEWDEV    61827
#define IDS_SUBSTATION_CHANGE_CAP       61828
#define IDS_FOLLOW_DISCONNECT           61829
#define IDS_MAINTAIN_DEPARTMENT         61830
#define IDS_LINE_TOTALLENGTH            61831
#define IDS_FAULTPOINT_M                61832
#define IDS_TOWER_LOCATION              61833
#define IDS_FAULT_REPORT                61834
#define IDS_FAULT_PHASE                 61835
#define IDS_FAULT_OVERVIEW              61836
#define IDS_FAULT_RECORDER_OSC          61837
#define IDS_EXCEL_STARTFAIL             61838
#define IDS_COMMON_LATEST               61839
#define IDS_COMMON_QUERY                61840
#define IDS_TIP_GEOGRAPH_NOTEXIST       61841
#define IDS_TIP_GEO_EDIT                61842
#define IDS_TIP_GEO_STATIONONLY         61843
#define IDS_TIP_GEO_CHANGEPOSITION      61844
#define IDS_TIP_SAVE_FINISHED           61845
#define IDS_TIP_GEO_MINIMUM             61846
#define IDS_TOOLBAR_CONNECT             61847
#define IDS_TOOLBAR_DEVICETREE          61848
#define IDS_TOOLBAR_LOG                 61849
#define IDS_TOOLBAR_GEO                 61850
#define IDS_TOOLBAR_STATIONGRPHA        61851
#define IDS_TOOLBAR_STATIONCOMMU        61852
#define IDS_TOOLBAR_STATIONINFO         61853
#define IDS_TOOLBAR_DEVICECOMMU         61854
#define IDS_TOOLBAR_DEVICERUN           61855
#define IDS_TOOLBAR_FAULTREPORT         61856
#define IDS_TOOLBAR_ACTION              61857
#define IDS_TOOLBAR_ALARM               61858
#define IDS_TOOLBAR_OSC                 61859
#define IDS_TOOLBAR_DIGITAL             61860
#define IDS_TOOLBAR_LOCATION            61861
#define IDS_TOOLBAR_SYSALARM            61862
#define IDS_TOOLBAR_BATCHCALL           61863
#define IDS_TOOLBAR_COMMONFILE          61864
#define IDS_TOOLBAR_HISQUERY            61865
#define IDS_TOOLBAR_ALARMSTAT           61866
#define IDS_TOOLBAR_SYSCONF             61867
#define IDS_TOOLBAR_ABOUT               61868
#define IDS_TOOLBAR_EXIT                61869
#define IDS_DOCK_DEVICETABLE            61870
#define IDS_DOCK_OUTPUT                 61871
#define IDS_DOCK_DEVICETREE             61872
#define IDS_DOCK_OUTPUT_OUT             61873
#define IDS_DOCK_OUTPUT_REMIND          61874
#define IDS_INIT_STATIONCOMMU_VIEW      61875
#define IDS_INIT_GEO_VIEW               61876
#define IDS_INIT_PTPROP_VIEW            61877
#define IDS_INIT_FAULTREPORT_VIEW       61878
#define IDS_INIT_ACTION_VIEW            61879
#define IDS_INIT_ALARM_VIEW             61880
#define IDS_INIT_RECODER_VIEW           61881
#define IDS_INIT_STATIONINFO_VIEW       61882
#define IDS_INIT_DIGITAL_VIEW           61883
#define IDS_INIT_DEVCOMMU_VIEW          61884
#define IDS_INIT_DEVRUN_VIEW            61885
#define IDS_INIT_SYSALARM_VIEW          61886
#define IDS_INIT_CROSS_VIEW             61887
#define IDS_INIT_EVENTI_VIEW            61888
#define IDS_INIT_EVENTII_VIEW           61889
#define IDS_INIT_EVENTIII_VIEW          61890
#define IDS_INIT_TESTING_VIEW           61891
#define IDS_INIT_DISTANCE_VIEW          61892
#define IDS_TIP_EXITCONFIRM             61893
#define IDS_REINIT_STATION              61894
#define IDS_REINIT_CLOSE_PTPROP         61895
#define IDS_REINIT_CLOSE_WRPROP         61896
#define IDS_REINIT_CLOSE_COMMONFILE     61897
#define IDS_REINIT_CLOSE_BATCHCALL      61898
#define IDS_REINIT_CLOSE_AUTOCALLCONF   61899
#define IDS_REINIT_CLOSE_AUTOCALLRESULT 61900
#define IDS_RELOAD_STATIONCOMMU         61901
#define IDS_RELOAD_STATIONMAP           61902
#define IDS_RELOAD_STATIONDEV           61903
#define IDS_RELOAD_DEVTREE              61904
#define IDS_RELOAD_ACTION               61905
#define IDS_RELOAD_ALARM                61906
#define IDS_RELOAD_DIGITAL              61907
#define IDS_RELOAD_FAULTREPORT          61908
#define IDS_RELOAD_OSC                  61909
#define IDS_RELOAD_DEVCOMMU             61910
#define IDS_RELOAD_DEVRUNSTATUS         61911
#define IDS_RELOAD_SYSALARM             61912
#define IDS_RELOAD_TESTING              61913
#define IDS_RELOAD_EVENTI               61914
#define IDS_RELOAD_EVENTII              61915
#define IDS_RELOAD_EVENTIII             61916
#define IDS_RELOAD_STATIONINFO          61917
#define IDS_RELOAD_COMPLETED            61918
#define IDS_COMMON_CLASS                61919
#define IDS_COMMON_CONTENT              61920
#define IDS_PACK_SELRELAYS              61921
#define IDS_PACK_RELAY_TOOMUCH          61922
#define IDS_PACK_NOEVENT                61923
#define IDS_PACK_EMPTY                  61924
#define IDS_PACK_SAVEPACKAGE_FAIL       61925
#define IDS_PACK_SAVEEVENT_FAIL         61926
#define IDS_PACK_SUCCESS                61927
#define IDS_PACK_NAME_PREFIX            61928
#define IDS_EVENT_RELATIVETIME          61929
#define IDS_COMMON_UNKNOWN_DEV          61930
#define IDS_TIP_OPEN_PRINTTEMPLATE_FAIL 61931
#define IDS_LATEST_ACTION               61932
#define IDS_FUN_ALARM                   61933
#define IDS_LATEST_ALARM                61934
#define IDS_COMMON_REALTIME_VALUE       61935
#define IDS_COMMON_NAME                 61936
#define IDS_COMMON_CODE                 61937
#define IDS_COMMON_UNIT                 61938
#define IDS_CALL_FAIL                   61939
#define IDS_CALLFAIL_UNSUPPORT          61940
#define IDS_BTN_CALLANALOG              61941
#define IDS_BTN_CALLDIGITAL             61942
#define IDS_CASE_COMMISSIONING          61943
#define IDS_CASE_CEASING                61944
#define IDS_CASE_OPENING                61945
#define IDS_CASE_CLOSING                61946
#define IDS_MODEL_VOLTAGE               61947
#define IDS_SECPROP_NOTE                61948
#define IDS_COMMON_UNKNOWN_SUBSTATION   61949
#define IDS_SUSPEND_YES                 61950
#define IDS_SUSPEND_NO                  61951
#define IDS_BTN_MOREINFO                61952
#define IDS_BTN_HIDEINFO                61953
#define IDS_BTN_CALLPROPERTY            61954
#define IDS_BTN_CALLTIME                61955
#define IDS_BTN_FORCE_SYNCTIME          61956
#define IDS_BTN_SIGNALRETURN            61957
#define IDS_CALL_BUSY                   61958
#define IDS_SYNCTIME_SUCCESS            61959
#define IDS_SYNCTIME_FAIL               61960
#define IDS_SIGNALRETURN_SUCCESS        61961
#define IDS_SIGNALRETURN_FAIL           61962
#define IDS_ACTION_CHR                  61963
#define IDS_ACTION_SIGNAL               61964
#define IDS_FAULTREPORT_UPDATE_SUCCESS  61965
#define IDS_PTNOTE_ITEM                 61966
#define IDS_PTNOTE_CONTENT              61967
#define IDS_COMMON_MODIFYTIME           61968
#define IDS_COMMON_MODIFY               61969
#define IDS_COMMON_DELETE               61970
#define IDS_PTNOTE_UPDATE_FAIL          61971
#define IDS_COMMON_DELETE_CONFIRM       61972
#define IDS_PTNOTE_DELETE_FAIL          61973
#define IDS_PTNOTE_CREATE_FAIL          61974
#define IDS_TIP_OPENDIR                 61975
#define IDS_SOURCE_SUBSTATIONDB         61976
#define IDS_SOURCE_LOCALDB              61977
#define IDS_DOWNOSC_BY_LOCAL            61978
#define IDS_DOWNOSC_SELLIST             61979
#define IDS_OPENFAIL_NOTDOWN            61980
#define IDS_SETTING_CURRENTZONE         61981
#define IDS_SETTING_ORDER               61982
#define IDS_POINT_GROUP                 61983
#define IDS_POINT_ITEM                  61984
#define IDS_POINT_STEP                  61985
#define IDS_POINT_MAXMIN                61986
#define IDS_POINT_PRECISION             61987
#define IDS_POINT_DATATYPE              61988
#define IDS_POINT_LOWERLIMIT            61989
#define IDS_POINT_UPPERLIMIT            61990
#define IDS_POINT_CURRENT_VALUE         61991
#define IDS_DATATYPE_FLOAT              61992
#define IDS_DATATYPE_INT                61993
#define IDS_DATATYPE_CONTROL16          61994
#define IDS_DATATYPE_STRING             61995
#define IDS_DATATYPE_CONTROL2           61996
#define IDS_COMMON_PARAMETER            61997
#define IDS_ZONE_UNKNOWN_EDITZONE       61998
#define IDS_CALLZONG_FAIL_BEFORE_MODIFY 61999
#define IDS_MODIFY_SETTING_FAIL         62000
#define IDS_MODIFY_ZONE_FAIL            62001
#define IDS_COMMON_RUN                  62002
#define IDS_CALL_EDITZONE_FAIL          62003
#define IDS_ZONE_RUN                    62004
#define IDS_ZONE_EDIT                   62005
#define IDS_ZONE_AUTOCALL_SUCCESS       62006
#define IDS_BTN_CALLSETTING             62007
#define IDS_BTN_CALLZONE                62008
#define IDS_MODIFY_SETTING              62009
#define IDS_MODIFY_ZONE                 62010
#define IDS_BTN_CANCEL_MODIFY           62011
#define IDS_CANCEL_SWITCH               62012
#define IDS_TIP_EDIT_SETTING            62013
#define IDS_VERIFY_MODIFYSETTING_CONFIRM 62014
#define IDS_COMMON_CHANGETO             62015
#define IDS_COMMON_FROM                 62016
#define IDS_EXECUTE_MODIFYSETTING_CONFIRM 62017
#define IDS_VERIFY_MODIFYSETTING_FAIL   62018
#define IDS_EXECUTE_MODIFYSETTING_FAIL  62019
#define IDS_EXECUTE_MODIFYSETTING_SUCCESS 62020
#define IDS_TIP_EDIT_ZONE               62021
#define IDS_TIP_SELECT_ZONE             62022
#define IDS_TIP_ZONEID_ERROR            62023
#define IDS_VERIFY_SUCCESS              62024
#define IDS_ZONE_SWITCHTO               62025
#define IDS_VERIFY_FAIL                 62026
#define IDS_VERIFY_SWITCHZONE_FAIL      62027
#define IDS_EXECUTE_SWITCHZONE_SUCCESS  62028
#define IDS_EXECUTE_SWITCHZONE_FAIL     62029
#define IDS_COMMON_OTHER                62030
#define IDS_MODIFYSETTING_SELZONE       62031
#define IDS_MODIFYSETTING_NOTCURRENTZONE 62032
#define IDS_MODIFYSETTING_NOTPARAM      62033
#define IDS_TIP_QUIT_EDITMODE           62034
#define IDS_SWITCHZONE_ONLYONE          62035
#define IDS_MODIFYSETTING_EDITZONE      62036
#define IDS_EXECUTE_MODIFYSOFT_FAIL     62037
#define IDS_EXECUTE_MODIFYSOFT_SUCCESS  62038
#define IDS_BTN_CALLSOFT                62039
#define IDS_BTN_MODIFYSOFT              62040
#define IDS_TIP_EDIT_SOFT               62041
#define IDS_MODIFYSOFT_CHECK            62042
#define IDS_EXECUTE_MODIFYSOFT_CONFIRM  62043
#define IDS_VERIFY_MODIFYSOFT_FAIL      62044
#define IDS_SELECT_DIR                  62045
#define IDS_STYLE_COMMON                62046
#define IDS_STYLE_SOUTHNET              62047
#define IDS_STYLE_COUNTRYNET            62048
#define IDS_STYLE_CUSTOMIZE             62049
#define IDS_COMMON_ERROR                62050
#define IDS_COMMON_DURATION             62051
#define IDS_COMMU_TEST                  62052
#define IDS_SELECT_SHOW_COLUMN          62054
#define IDS_CALL_CALLING                62055
#define IDS_TESTSTATION_CANCEL          62056
#define IDS_STATIONMAP_SHOWERROR        62057
#define IDS_FAULTREPORT_ISTRUEFALUT     62058
#define IDS_FAULTREPORT_ISOVERHAUL      62059
#define IDS_FAULTREPORT_ISSAVED         62060
#define IDS_FAULTREPORT_ISTYPICAL       62061
#define IDS_COMMON_DETAILREASON         62062
#define IDS_OVERHUAL_YES                62063
#define IDS_OVERHUAL_NO                 62064
#define IDS_COMMON_PLAYBACK             62065
#define IDS_TIP_FAULTREPORT_SWITCH      62066
#define IDS_ARCHIVE_YES                 62067
#define IDS_ARCHIVE_NO                  62068
#define IDS_TYPICAL_YES                 62069
#define IDS_TYPICAL_NO                  62070
#define IDS_TIP_FAULTREPORT_NO_PLAYBACK_SCRIPT 62071
#define IDS_PUBLICTO_WEB                62072
#define IDS_FAULTREPORT_NEW             62073
#define IDS_TIP_DELETE_FAULTREPORT      62074
#define IDS_TIP_OPEN_FAULTREPORT_TEMPLATE_FAIL 62075
#define IDS_COMMON_AWAYFROM             62076
#define IDS_TIP_WAVESHAPE_NOTFOUND      62077
#define IDS_TIP_CLICK_OPENWAVE          62078
#define IDS_FAULTREPORT_MAIN_LOCATION   62079
#define IDS_RECLOSE_NOTCLOSE            62080
#define IDS_TIP_FAULTREPORT_EMPTY       62081
#define IDS_FAULTREPORT_EXPORT          62082
#define IDS_FAULT_SINGLEPHASE           62083
#define IDS_FAULT_BETWEENPHASE          62084
#define IDS_QUERY_CONDITION             62085
#define IDS_FAULTREPORT_QUERY_COUNT     62086
#define IDS_FAULT_RECLOSE_TIME          62087
#define IDS_FAULT_NOFAULT               62088
#define IDS_MODEL_OVERHUALUNIT          62089
#define IDS_TITLE_DEV_COMMUSTATUS       62090
#define IDS_TITLE_DEV_COMMUON           62091
#define IDS_TITLE_DEV_COMMUOFF          62092
#define IDS_TITLE_DEV_COMMUUNKNOWN      62093
#define IDS_EVENTCLASS_I                62094
#define IDS_EVENTCLASS_II               62095
#define IDS_EVENTCLASS_III              62096
#define IDS_EVENTCLASS_DEBUG            62097
#define IDS_ORDER_STRATEGY              62098
#define IDS_COMMON_GATEWAY              62099
#define IDS_COMMON_MODEL                62100
#define IDS_HISTORY_RECORD              62101
#define IDS_ORDERSTRATEGY_SMART         62102
#define IDS_ORDERSTRATEGY_ALL           62103
#define IDS_DEVICE_INFO                 62104
#define IDS_VALUE_BEFORE                62105
#define IDS_VALUE_AFTER                 62106
#define IDS_BTN_REMOTESTART             62107
#define IDS_REMOTESTART_SUCCESS         62108
#define IDS_REMOTESTART_FAIL            62109
#define IDS_TIP_APP_EXIST               62110
#define IDS_TIP_FAULTAPP_NOTFOUND       62111
#define IDS_TIP_QUERYAPP_NOFOUND        62112
#define IDS_TIP_ALARMSTATAPP_NOFOUND    62113
#define IDS_TIP_PLAYBACKAPP_NOTFOUND    62114
#define IDS_COMMON_NONEED_DEAL          62115
#define IDS_STARTING_MOUNT              62116
#define IDS_COMMON_USER                 62117
#define IDS_COMMON_LOGIN                62118
#define IDS_STARTING_DEVICETREE         62119
#define IDS_STARTING_DEFAULTSTATION     62120
#define IDS_STARTING_LOADDATA_COMPLETED 62121
#define IDS_TIP_LOGOUT_FAIL             62122
#define IDS_COMMUSERVER_CONVENTION      62123
#define IDS_COMMUSERVER_61850           62124
#define IDS_TIP_RECONNECTING            62125
#define IDS_DISCONNECT_COMMUSERVER      62126
#define IDS_CONNECT_COMMUSERVER         62127
#define IDS_COMMON_WRITEOFF             62128
#define IDS_TIP_RESTART_APP             62129
#define IDS_NOGRAPH_REASON1             62130
#define IDS_NOGRAPH_REASON2             62131
#define IDS_NOGRAPH_REASON3             62132
#define IDS_TIP_NOT_SUBSTATION_MODE     62133
#define IDS_TIP_DEVICE_NOTFOUND         62134
#define IDS_TIP_EXCEPTION               62135
#define IDS_TIP_DRAFT_NOTFOUND          62136
#define IDS_DBSERVER_DISCONNECT         62137
#define IDS_REASON_FOR                  62138
#define IDS_ABOUT_VERINFO               62139
#define IDS_BTN_CLOSE                   62140
#define IDS_ABOUT_REGISTER_USER         62141
#define IDS_ABOUT_SERIALNUMBER          62142
#define IDS_ABOUT_COMPANY_NAME          62143
#define IDS_ABOUT_INTERNALNAME          62144
#define IDS_LANG_CODE                   62145
#define IDS_CANCEL_NULL                 62146
#define IDS_USERGROUP_RUNNER            62147
#define IDS_USERGROUP_OPERATOR          62148
#define IDS_USERGROUP_MONITOR           62149
#define IDS_RUNSTATUS_HANGOUT           62150
#define IDS_DZ_MOD_STATE_0              62151
#define IDS_DZ_MOD_STATE_1              62152
#define IDS_DZ_MOD_STATE_2              62153
#define IDS_DZ_MOD_STATE_3              62154
#define IDS_DZ_MOD_STATE_4              62155
#define IDS_DZ_MOD_STATE_5              62156
#define IDS_PTSET_VERIFY_0              62157
#define IDS_PTSET_VERIFY_1              62158
#define IDS_CHECK_RUNNER                62159
#define IDS_VALIDATE_RUNNER             62160
#define IDS_COLUMN_VALUE_0              62161
#define IDS_COLUMN_VALUE_1              62162
#define IDS_DOCK_MSG                    62163
#define IDS_USERGROUP_SUPER             62164
#define IDS_COLUMN_VALUE_2              62165
#define IDS_PTS_MOD_PROGRESS            62166
#define IDS_WINDOW_MSG                  62167
#define IDS_FUNC_HANGOUTSTATUS          62168
#define IDS_HANGOUT_STATUS              62169
#define IDS_HANGOUTING_STATUS           62170
#define IDS_HANGOUTNONE_STATUS          62171
#define IDS_VALIDATE_USERALREADYLOGIN_ERROR 62172

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        347
#define _APS_NEXT_COMMAND_VALUE         32982
#define _APS_NEXT_CONTROL_VALUE         1430
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
